# This is a basic workflow to help you get started with Actions

name: ESLint CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # setup
      - uses: actions/checkout@v2
      - run: yarn
      # run linter
      - name: Lint using ESLint
        run: yarn run eslint .
